# Generated by Django 5.0.3 on 2024-03-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='age_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_group',
            field=models.CharField(choices=[('Indskoling', 'Indskoling'), ('Mellemtrin', 'Mellemtrin'), ('Udskoling', 'Udskoling')], default='Indskoling', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='age_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
