# Generated by Django 5.0.3 on 2024-03-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0002_schoolclass_age_number_schoolclass_class_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employment_category', models.CharField(choices=[('Lærer', 'Lærer'), ('Pædagog', 'Pædagog'), ('Pædagogmedhjælper/Pædagogisk assistent', 'Pædagogmedhjælper/Pædagogisk assistent')], max_length=100)),
                ('employment_grade', models.IntegerField(default=37)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('classroom', models.CharField(max_length=100)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skole.schoolclass')),
                ('teachers', models.ManyToManyField(to='skole.staff')),
            ],
        ),
    ]
