# Generated by Django 5.0.3 on 2024-03-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0004_alter_schoolclass_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='class_teacher',
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_teachers',
            field=models.ManyToManyField(blank=True, related_name='class_teachers', to='skole.staff'),
        ),
    ]
