# Generated by Django 5.0.3 on 2024-03-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0006_schoolfee_student_school_fee_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skole.schoolfee'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_fee_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Trin 1'), (2, 'Trin 2'), (3, 'Trin 3')], default=1, null=True),
        ),
    ]
