# Generated by Django 5.0.3 on 2024-03-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0007_student_school_fee_alter_student_school_fee_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school_fee_level',
        ),
        migrations.AddField(
            model_name='schoolfee',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolfee',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schoolfee',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
