# Generated by Django 5.0.3 on 2024-03-29 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0008_remove_student_school_fee_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('price_pr_lesson', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skole.employmentcategory'),
        ),
    ]
