# Generated by Django 5.0.3 on 2024-03-29 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skole', '0009_employmentcategory_alter_staff_employment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='skole.school'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='skole.schoolclass'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teachers',
            field=models.ManyToManyField(related_name='taught_lessons', to='skole.staff'),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_classes', to='skole.team'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='skole.employmentcategory'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='skole.schoolclass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='skole.schoolfee'),
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='skole.department'),
        ),
    ]
