# Generated by Django 5.0.3 on 2024-04-12 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0010_alter_department_school_alter_lesson_school_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="school_fee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="skole.schoolfee",
            ),
        ),
    ]
