# Generated by Django 5.0.6 on 2024-07-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("skole", "0011_alter_student_school_fee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["name"],
                "verbose_name": "Elev",
                "verbose_name_plural": "Elever",
            },
        ),
        migrations.AlterField(
            model_name="student",
            name="age_number",
            field=models.IntegerField(
                blank=True, help_text="Indtast klassetrin", null=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Indtast fødselsdato i formatet YYYY-MM-DD",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(help_text="Elevens fulde navn", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="schoolclass",
            field=models.ForeignKey(
                help_text="Vælg den klasse, som eleven tilhører",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="skole.schoolclass",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="school_fee",
            field=models.ForeignKey(
                blank=True,
                help_text="Vælg takst (kriterie) i tildelingsmodellen",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="skole.schoolfee",
            ),
        ),
    ]
